[colors.primary]
background = "{{colors.surface.default.hex}}"
foreground = "{{colors.on_surface.default.hex}}"

[colors.cursor]
text = "{{colors.on_surface.default.hex}}"
cursor = "{{colors.on_surface_variant.default.hex}}"

[colors.search.matches]
foreground = "{{colors.surface_variant.default.hex}}"
background = "{{colors.tertiary.default.hex}}"

[colors.search.focused_match]
foreground = "{{colors.surface_variant.default.hex}}"
background = "{{colors.primary.default.hex}}"

[colors.footer_bar]
foreground = "{{colors.surface_variant.default.hex}}"
background = "{{colors.inverse_surface.default.hex}}"

[colors.hints.start]
foreground = "{{colors.surface_variant.default.hex}}"
background = "{{colors.secondary.default.hex}}"

[colors.hints.end]
foreground = "{{colors.surface_variant.default.hex}}"
background = "{{colors.secondary.default.hex}}"

[colors.selection]
text = "{{colors.background.default.hex}}"
background = "{{colors.primary.default.hex}}"


# Catpuccin mocha

[colors.normal]
black = "#45475a"
red = "#f38ba8"
green = "#a6e3a1"
yellow = "#f9e2af"
blue = "#89b4fa"
magenta = "#f5c2e7"
cyan = "#94e2d5"
white = "#bac2de"

[colors.bright]
black = "#585b70"
red = "#f38ba8"
green = "#a6e3a1"
yellow = "#f9e2af"
blue = "#89b4fa"
magenta = "#f5c2e7"
cyan = "#94e2d5"
white = "#a6adc8"

[[colors.indexed_colors]]
index = 16
color = "#fab387"

[[colors.indexed_colors]]
index = 17
color = "#f5e0dc"
